### ISSUE TITLE
HELP CODE

### ISSUE THREAD

**Issue by SapkaliBeyfendi** [mirko93s/Chill#4]
(node:801) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'ensure' of undefined
    at ensureGuildSettings (/app/functions.js:452:21)
    at module.exports (/app/events/message.js:6:5)
    at Client.emit (events.js:198:13)
    at MessageCreateAction.handle (/rbd/pnpm-volume/2eee3377-842e-431b-a1a6-5bcfb3728442/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/rbd/pnpm-volume/2eee3377-842e-431b-a1a6-5bcfb3728442/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/rbd/pnpm-volume/2eee3377-842e-431b-a1a6-5bcfb3728442/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/rbd/pnpm-volume/2eee3377-842e-431b-a1a6-5bcfb3728442/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/rbd/pnpm-volume/2eee3377-842e-431b-a1a6-5bcfb3728442/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/rbd/pnpm-volume/2eee3377-842e-431b-a1a6-5bcfb3728442/node_modules/discord.js/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:198:13)
(node:801) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:801) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'ensure' of undefined
    at ensureGuildSettings (/app/functions.js:452:21)
    at module.exports (/app/events/message.js:6:5)
    at Client.emit (events.js:198:13)
    at MessageCreateAction.handle (/rbd/pnpm-volume/2eee3377-842e-431b-a1a6-5bcfb3728442/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/rbd/pnpm-volume/2eee3377-842e-431b-a1a6-5bcfb3728442/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/rbd/pnpm-volume/2eee3377-842e-431b-a1a6-5bcfb3728442/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/rbd/pnpm-volume/2eee3377-842e-431b-a1a6-5bcfb3728442/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/rbd/pnpm-volume/2eee3377-842e-431b-a1a6-5bcfb3728442/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/rbd/pnpm-volume/2eee3377-842e-431b-a1a6-5bcfb3728442/node_modules/discord.js/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:198:13)
(node:801) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

**Comment by mirko93s** [comment]
Did you change any code anywhere? What were you doing when you got this error? I never got an error with that function

**Comment by mirko93s** [comment]
This is not a bug related to my bot, if you need further help contact me on discord
